name: Continuous Integration (CI)

## Run CI jobs on all branches by default
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4

      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70

      - name: Run unit tests
        run: ./gradlew test